## Custom dataset:
In pytorch datasets are classes

In [5]:
import torch 
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self):
        self.x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
        self.y = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

    def __len__(self):
        #How big dataset is
        return len(self.x)

    def _getitem__(self, index):
        #to get one sample
        return self.x[index], self.y[index]

## DataLoader:
DataLoader loads data in batches.

In [6]:
from torch.utils.data import DataLoader

dataset = MyDataset()
loader = DataLoader(dataset, batch_size=2, shuffle=True)

now our training loop becomes:

    for epoch in range(1000):
        for x_batch, y_batch in loader:

            y_pred = model(x_batch)
            loss = loss_fn(y_pred, y_batch)
    
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

This can also be done without using a custom class, by using a util called **TensorDataset**

In [8]:
from torch.utils.data import TensorDataset

x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

dataset = TensorDataset(x,y)
loader = DataLoader(dataset, batch_size=2, shuffle=True)

In [9]:
for x_batch, y_batch in loader:
    print(x_batch,'\n', y_batch)

tensor([[4.],
        [2.]]) 
 tensor([[9.],
        [5.]])
tensor([[1.],
        [3.]]) 
 tensor([[3.],
        [7.]])


If you are using csv data then for x and y you can use this on a pandas dataframe:

    X = torch.tensor(df.iloc[:, :-1].values, dtype=torch.float32)
    y = torch.tensor(df.iloc[:, -1].values, dtype=torch.float32).unsqueeze(1)