## Main objects in PyTorch:
* Tensors
* Gradients
* Computational Graphs
* Optimizers
* Loss Functions
* Model

## Tensors:
PyTorch tensors are like NumPy arrays but can:
* Run on GPU
* Track gradients
* Be part of neural network graph

In [1]:
import torch 

x = torch.tensor([1.0,2.0,3.0])
print(x)

tensor([1., 2., 3.])


In [2]:
A = torch.tensor([[1,2],
                [3,4]])
print(A)

tensor([[1, 2],
        [3, 4]])


Since PyTorch tensors are numpy arrays all the methods applicable to them are also appplicable to these tensors as follows:

In [3]:
A.ndim

2

In [4]:
A.shape

torch.Size([2, 2])

In [8]:
print(torch.ones(3,3))
print(torch.zeros(2,2))
print(torch.rand(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.9307, 0.3928, 0.7889],
        [0.3621, 0.1725, 0.4459],
        [0.6056, 0.7448, 0.5406]])


## GPU 
Everything must be on the same device:
* model
* inputs
* labels

In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.tensor([2.0,3.0]).to(device)

## Auto-gradient:
PyTorch automatically computes gradients using backpropagation.

In [12]:
x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x + 1
y.backward()

print(x.grad) #dy/dx = 2x + 3

tensor(7.)


## Building a nural network in PyTorch:

In [15]:
import torch.nn as nn

#model
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1) #here 2 is number of input features, and 1 is output shape....weights are initialized randomly if no mentioned

    def forward(self, x):
        return self.linear(x)

#usage
model = MyModel()
output = model(torch.tensor([[1.0,2.0]]))

In [16]:
print(output)

tensor([[0.3288]], grad_fn=<AddmmBackward0>)


## Training Loop:
This is the standard PyTorch training loop:

In [17]:
import torch.optim as optim

model = nn.Linear(1,1)
optimizer = optim.SGD(model.parameters(), lr=0.01)
loss_fn = nn.MSELoss()

for epoch in range(100):
    x = torch.tensor([[1.0]])
    y = torch.tensor([[2.0]])

    pred = model(x)
    loss = loss_fn(pred,y)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

Forward pass → 
Compute loss → 
Backward pass → 
Optimizer step → 
Zero gradients